# SITE CONFIGURATION
title: 爱贝睿技术团队 # your site title
author: https://github.com/iBrainTech # You :P
description: > # Meta description of Homepage
  爱贝睿技术团队实践分享
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ibraintech.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: 爱贝睿技术团队
  links:
    - https://juejin.im/user/5b4d5690f265da0f7238688d
    - https://github.com/iBrainTech

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}

tagline: >
  聪明养育，从脑开始。

hero_img: posts/ibraintech_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

juejin_username: 5b4d5690f265da0f7238688d # replace with your_twitter_username or comment to remove link from footer
github_username:  iBrainTech # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: ibraintech # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
